### ISSUE TITLE
Moralis Server

### ISSUE THREAD

**Issue by abedgithup** [PatrickAlphaC/nextjs-nft-marketplace-moralis-fcc#17]
when I type this code ( npm run  moralis:sync), I run into this error:

> my-app@0.1.0 moralis:sync
> moralis-admin-cli connect-local-devchain --chain hardhat --moralisSubdomain cxdjddn5lxdh.usemoralis.com --frpcPath ./frp/frpc

Starting connection to Hardhat
exec error: Error: Command failed: "./frp/frpc" http -s cxdjddn5lxdh.usemoralis.com:7000 -t GCqiUSu6wG -l 8545 -d cxdjddn5lxdh.usemoralis.com
'"./frp/frpc"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AnneCh** [comment]
I've noticed that Moralis has upgraded since the video was released, maybe that's the issue and the `'"./frp/frpc"` is no longer active ? 

@PatrickAlphaC on a similar topic (feel free to remove my comment if I should open a new issue for it), should we follow your way and use Moralis V1, or should we try to install the server following Moralis' new version? If doing the latter, will that have a big impact on the rest of the lesson?

**Comment by r0ushann** [comment]
cant find api secret on the new moralis dashboard !
@PatrickAlphaC  ?

**Comment by hineshmiyani** [comment]
> 

@r0ushann Yeah, You can!
Please follow this steps:

![image](https://user-images.githubusercontent.com/48402698/191449024-80ae6375-86d8-4443-a6dd-fc9902cfd899.png)

**Comment by r0ushann** [comment]
Thanks @hineshmiyani

**Comment by r0ushann** [comment]
@abedgithup  i think u didn't configured it correctly.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/


Thank you!
